from tkinter import*
root = Tk()
root.geometry("1000x1000")
#root.resizable(0,0)
var=IntVar()
l1=Label(root,text="Registration Form",font=('Arial',15),bg='blue',fg='red')
l1.grid(row=0,column=5,pady=0)
l2=Label(root,text="Name",font=('Arial',15),bg='yellow',fg='red')
l2.grid(row=1,column=0,pady=15)
e1=Entry(root,font=('Arial',15),fg='black')
e1.grid(row=1,column=6,pady=15)
l3=Label(root,text="Father Name",font=('Arial',15),bg='yellow',fg='red')
l3.grid(row=2,column=0,pady=15)
e3=Entry(root,font=('Arial',15),fg='black')
e3.grid(row=2,column=6,pady=15)
l4=Label(root,text="Mother Name",font=('Arial',15),bg='yellow',fg='red')
l4.grid(row=3,column=0,pady=15)
e4=Entry(root,font=('Arial',15),fg='black')
e4.grid(row=3,column=6,pady=15)
l5=Label(root,text="DOB",font=('Arial',15),bg='yellow',fg='red')
l5.grid(row=4,column=0,pady=15)
e5=Entry(root,font=('Arial',15),fg='black')
e5.grid(row=4,column=6,pady=15)
l6=Label(root,text="Mob no.",font=('Arial',15),bg='yellow',fg='red')
l6.grid(row=5,column=0,pady=15)
e6=Entry(root,font=('Arial',15),fg='black')
e6.grid(row=5,column=6,pady=15)
l7=Label(root,text="Gender",font=('Arial',15),bg='yellow',fg='red')
l7.grid(row=6,column=0,pady=15)
r1=Radiobutton(root,text="Male",font=("Arial",15),variable=var,value=1)
r1.grid(row=6,column=5,pady=15)
r2=Radiobutton(root,text="Female",font=("Arial",15),variable=var,value=2)
r2.grid(row=6,column=6,pady=15)
l8=Label(root,text="E-mail",font=('Arial',15),bg='yellow',fg='red')
l8.grid(row=7,column=0,pady=15)
e8=Entry(root,font=('Arial',15),fg='black')
e8.grid(row=7,column=6,pady=15)
l9=Label(root,text="Address",font=('Arial',15),bg='yellow',fg='red')
l9.grid(row=8,column=0,pady=15)
e9=Entry(root,font=('Arial',15),fg='black')
e9.grid(row=8,column=6,pady=15)
l10=Label(root,text="District",font=('Arial',15),bg='yellow',fg='red')
l10.grid(row=9,column=0,pady=15)
e10=Entry(root,font=('Arial',15),fg='black')
e10.grid(row=9,column=6,pady=15)
l11=Label(root,text="State",font=('Arial',15),bg='yellow',fg='red')
l11.grid(row=10,column=0,pady=15)
e11=Entry(root,font=('Arial',15),fg='black')
e11.grid(row=10,column=6,pady=15)
l12=Label(root,text="Country",font=('Arial',15),bg='yellow',fg='red')
l12.grid(row=11,column=0,pady=20)
e12=Entry(root,font=('Arial',15),fg='black')
e12.grid(row=11,column=6,pady=15)
b=Button(root,text="Submit",font=("Arial",15),fg="cyan")
b.grid(row=12,column=5,pady=15)
root.mainloop()






